import React from "react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/Marketplace.module.css";

const Marketplace = () => {
  const [type, setType] = React.useState([]);

  console.log(type);

  return (
    <div>
      <Head>
        <title>Solkicks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />

        <div className={styles.pageWrapper}>
          <div className={styles.pageContainer}>
            <div className={styles.headerWrapper}>
              <h1>Marketplace</h1>
            </div>
            <div className={styles.marketplaceSort}>
              <div className={styles.sortFilter}>
                <select className={styles.sortSelect}>
                  <option value="most-price">Ask Price, Descending</option>
                  <option value="least-price">Ask Price, Ascending</option>
                  <option value="most-recent">Most Recent</option>
                  <option value="least-recent" selected="">
                    Least Recent
                  </option>
                </select>
              </div>
            </div>
            <div className={styles.marketPlaceContent}>
              <div className={styles.sideBarContent}>
                <div className={styles.analytics}>
                  <div className={styles.floorPrice}>
                    <div className={styles.price}>$126.69</div>
                    <div className={styles.label}>Floor Price</div>
                  </div>
                  <div className={styles.volumeTraded}>
                    <div className={styles.price}>$1.89M</div>
                    <div className={styles.label}>
                      <select className={styles.volumeSelect}>
                        <option
                          className={styles.volumeOption}
                          value="lastDayVolume"
                        >
                          24h
                        </option>
                        <option
                          className={styles.volumeOption}
                          value="lastWeekVolume"
                        >
                          7d
                        </option>
                        <option
                          className={styles.volumeOption}
                          value="lastMonthVolume"
                        >
                          30d
                        </option>
                        <option
                          className={styles.volumeOption}
                          value="allTimeVolume"
                          selected=""
                        >
                          All Time
                        </option>
                      </select>
                      Volume
                    </div>
                  </div>
                </div>
                <div className={styles.filterContainer}>
                  <div className={styles.filterContainerHeading}>
                    <h1>Marketplace Filters</h1>
                    <div className={styles.clearFilter}>
                      <button type="button" className={styles.clearFilterBtn}>
                        <span className={styles.closeIcon}>
                          <svg
                            width="10"
                            height="10"
                            viewBox="0 0 12 12"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <path
                              d="M11 1L1 11 11 1z"
                              fill="currentColor"
                            ></path>
                            <path
                              d="M11 1L1 11"
                              stroke="currentColor"
                              strokeWidth="1.5"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                            ></path>
                            <path
                              d="M11 11L1 1l10 10z"
                              fill="currentColor"
                            ></path>
                            <path
                              d="M11 11L1 1"
                              stroke="currentColor"
                              strokeWidth="1.5"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                            ></path>
                          </svg>
                        </span>
                        Reset Filters
                      </button>
                    </div>
                  </div>

                  <div className={styles.filterAccordion}>
                    <summary className={styles.accordionHeading}>
                      <span style={{ display: "flex", alignItems: "center" }}>
                        Type <span className={styles.selectCount}>1</span>
                      </span>
                      <div className={styles.accResetBtn}>
                        <button type="button">Reset</button>
                      </div>
                      <svg
                        width="13"
                        height="8"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                        className="filter-accordion_icon__2DcQz"
                      >
                        <path
                          d="M12 1L6.5 7 1 1"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></path>
                      </svg>
                    </summary>

                    <div className={styles.accordionContent}>
                      <div>
                        <label className={styles.accordionLabel}>
                          <input
                            type="checkbox"
                            name="Base Pack"
                            className={styles.accordionChheckbox}
                            value="Base Pack"
                            // onClick={() => setType.push("Base Pack")}
                          />
                          Base Pack
                        </label>
                      </div>
                      <div>
                        <label className={styles.accordionLabel}>
                          <input
                            type="checkbox"
                            name="Character"
                            className={styles.accordionChheckbox}
                            value="Character"
                          />
                          Character
                        </label>
                      </div>
                      <div>
                        <label className={styles.accordionLabel}>
                          <input
                            type="checkbox"
                            name="Slime"
                            className={styles.accordionChheckbox}
                            value="Slime"
                          />
                          Slime
                        </label>
                      </div>
                    </div>
                  </div>

                  <div className={styles.filterAccordion}>
                    <summary className={styles.accordionHeading}>
                      <span style={{ display: "flex", alignItems: "center" }}>
                        Slime Score{" "}
                        <span className={styles.selectCount}>1</span>
                      </span>
                      <div className={styles.accResetBtn}>
                        <button type="button">Reset</button>
                      </div>
                      <svg
                        width="13"
                        height="8"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                        className="filter-accordion_icon__2DcQz"
                      >
                        <path
                          d="M12 1L6.5 7 1 1"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        ></path>
                      </svg>
                    </summary>

                    <div className={styles.accordionContent}>
                      <div>
                        <label className={styles.accordionLabel}>
                          <input
                            type="checkbox"
                            name="1"
                            className={styles.accordionChheckbox}
                            value="1"
                          />
                          1
                        </label>
                      </div>
                      <div>
                        <label className={styles.accordionLabel}>
                          <input
                            type="checkbox"
                            name="2"
                            className={styles.accordionChheckbox}
                            value="2"
                          />
                          2
                        </label>
                      </div>
                      <div>
                        <label className={styles.accordionLabel}>
                          <input
                            type="checkbox"
                            name="3"
                            className={styles.accordionChheckbox}
                            value="3"
                          />
                          3
                        </label>
                      </div>
                      <div>
                        <label className={styles.accordionLabel}>
                          <input
                            type="checkbox"
                            name="4"
                            className={styles.accordionChheckbox}
                            value="4"
                          />
                          4
                        </label>
                      </div>
                      <div>
                        <label className={styles.accordionLabel}>
                          <input
                            type="checkbox"
                            name="5"
                            className={styles.accordionChheckbox}
                            value="5"
                          />
                          5
                        </label>
                      </div>
                      <div>
                        <label className={styles.accordionLabel}>
                          <input
                            type="checkbox"
                            name="10"
                            className={styles.accordionChheckbox}
                            value="10"
                          />
                          10
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div className={styles.marketContent}>
                <div className={styles.contentWrapper}>
                  <div className={styles.productCardContainer}>
                    <span className={styles.imageContainer}>
                      <span className={styles.imageC} data-loading="false">
                        <img
                          alt="Phil DeVille #60 - Rarity: Ultra Rare, SeriesNumber: Rugrats x Hey Arnold!"
                          className={styles.productImage}
                          decoding="async"
                          height="330"
                          loading="lazy"
                          sizes=""
                          src="https://nickelodeon.xyz/nft-content/media/ORANGE/3a56b837-64e6-49de-b903-7efe9307571c/ef8e8ec1a9854c76346757cd2a03c41942a45f4504cd6b49005a6edf406ce724"
                          srcSet=""
                          width="323"
                        />
                      </span>
                    </span>
                    <div className={styles.productCardContainer}>
                      <div className={styles.cardTitle}>
                        <h3>Phil DeVille #60</h3>
                      </div>
                      <div className={styles.price}>
                        <span className={styles.ppPrice}>$1,500.00</span>
                      </div>
                    </div>
                  </div>

                  <div className={styles.productCardContainer}>
                    <span className={styles.imageContainer}>
                      <span className={styles.imageC} data-loading="false">
                        <img
                          alt="Phil DeVille #60 - Rarity: Ultra Rare, SeriesNumber: Rugrats x Hey Arnold!"
                          className={styles.productImage}
                          decoding="async"
                          height="330"
                          loading="lazy"
                          sizes=""
                          src="https://nickelodeon.xyz/nft-content/media/ORANGE/3a56b837-64e6-49de-b903-7efe9307571c/ef8e8ec1a9854c76346757cd2a03c41942a45f4504cd6b49005a6edf406ce724"
                          srcSet=""
                          width="323"
                        />
                      </span>
                    </span>
                    <div className={styles.productCardContainer}>
                      <div className={styles.cardTitle}>
                        <h3>Phil DeVille #60</h3>
                      </div>
                      <div className={styles.price}>
                        <span className={styles.ppPrice}>$1,500.00</span>
                      </div>
                    </div>
                  </div>

                  <div className={styles.productCardContainer}>
                    <span className={styles.imageContainer}>
                      <span className={styles.imageC} data-loading="false">
                        <img
                          alt="Phil DeVille #60 - Rarity: Ultra Rare, SeriesNumber: Rugrats x Hey Arnold!"
                          className={styles.productImage}
                          decoding="async"
                          height="330"
                          loading="lazy"
                          sizes=""
                          src="https://nickelodeon.xyz/nft-content/media/ORANGE/3a56b837-64e6-49de-b903-7efe9307571c/ef8e8ec1a9854c76346757cd2a03c41942a45f4504cd6b49005a6edf406ce724"
                          srcSet=""
                          width="323"
                        />
                      </span>
                    </span>
                    <div className={styles.productCardContainer}>
                      <div className={styles.cardTitle}>
                        <h3>Phil DeVille #60</h3>
                      </div>
                      <div className={styles.price}>
                        <span className={styles.ppPrice}>$1,500.00</span>
                      </div>
                    </div>
                  </div>

                  <div className={styles.productCardContainer}>
                    <span className={styles.imageContainer}>
                      <span className={styles.imageC} data-loading="false">
                        <img
                          alt="Phil DeVille #60 - Rarity: Ultra Rare, SeriesNumber: Rugrats x Hey Arnold!"
                          className={styles.productImage}
                          decoding="async"
                          height="330"
                          loading="lazy"
                          sizes=""
                          src="https://nickelodeon.xyz/nft-content/media/ORANGE/3a56b837-64e6-49de-b903-7efe9307571c/ef8e8ec1a9854c76346757cd2a03c41942a45f4504cd6b49005a6edf406ce724"
                          srcSet=""
                          width="323"
                        />
                      </span>
                    </span>
                    <div className={styles.productCardContainer}>
                      <div className={styles.cardTitle}>
                        <h3>Phil DeVille #60</h3>
                      </div>
                      <div className={styles.price}>
                        <span className={styles.ppPrice}>$1,500.00</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Marketplace;
